<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class WorkReviews {
	private $workreviews_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'workreviews_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'workreviews_page_init' ) );
	}

	public function workreviews_add_plugin_page() {
		add_options_page(
			'WorkReviews', // page_title
			'WorkReviews', // menu_title
			'manage_options', // capability
			'workreviews', // menu_slug
			array( $this, 'workreviews_create_admin_page' ) // function
		);
	}

	public function workreviews_create_admin_page() {
		$this->workreviews_options = get_option( 'workreviews_option_name' ); ?>

		<div class="wrap">
			<h2>WorkReviews</h2>
            <p>Отзывы о работе клининговой компании</p>
            <p><b>[work-reviews]</b> - шорткод для вставки отзывов</p>
		</div>
	<?php }

	public function workreviews_page_init() {
		register_setting(
			'workreviews_option_group', // option_group
			'workreviews_option_name', // option_name
			array( $this, 'workreviews_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'workreviews_setting_section', // id
			'Настройки', // title
			array( $this, 'workreviews_section_info' ), // callback
			'workreviews-admin' // page
		);
	}
}
if ( is_admin() )
	$workreviews = new WorkReviews();
