<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class WorkReviews {
	private $workreviews_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'workreviews_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'workreviews_page_init' ) );
	}

	public function workreviews_add_plugin_page() {
		add_options_page(
			'WorkReviews', // page_title
			'WorkReviews', // menu_title
			'manage_options', // capability
			'workreviews', // menu_slug
			array( $this, 'workreviews_create_admin_page' ) // function
		);
	}

	public function workreviews_create_admin_page() {
		$this->workreviews_options = get_option( 'workreviews_option_name' ); ?>

		<div class="wrap">
			<h2>WorkReviews</h2>
            <p>Отзывы о работе клининговой компании</p>
            <p><b>[work-reviews]</b> - шорткод для вставки отзывов</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'workreviews_option_group' );
					do_settings_sections( 'workreviews-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function workreviews_page_init() {
		register_setting(
			'workreviews_option_group', // option_group
			'workreviews_option_name', // option_name
			array( $this, 'workreviews_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'workreviews_setting_section', // id
			'Настройки', // title
			array( $this, 'workreviews_section_info' ), // callback
			'workreviews-admin' // page
		);

		add_settings_field(
			'nnm_0', // id
			'Nnm', // title
			array( $this, 'nnm_0_callback' ), // callback
			'workreviews-admin', // page
			'workreviews_setting_section' // section
		);
	}

	public function workreviews_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['nnm_0'] ) ) {
			$sanitary_values['nnm_0'] = sanitize_text_field( $input['nnm_0'] );
		}

		return $sanitary_values;
	}

	public function workreviews_section_info() {

	}

	public function nnm_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="workreviews_option_name[nnm_0]" id="nnm_0" value="%s">',
			isset( $this->workreviews_options['nnm_0'] ) ? esc_attr( $this->workreviews_options['nnm_0']) : ''
		);
	}

}
if ( is_admin() )
	$workreviews = new WorkReviews();

/*
 * Retrieve this value with:
 * $workreviews_options = get_option( 'workreviews_option_name' ); // Array of All Options
 * $nnm_0 = $workreviews_options['nnm_0']; // Nnm
 */